### ISSUE TITLE
CentOS Package

### ISSUE THREAD

**Issue by martinvelez** [DDNStorage/collectd#1]
The original **[collectd](https://collectd.org/download.shtml)** is packaged for several Linux distributions, like Ubuntu and CentOS.

Do you have any CentOS package available?

**Comment by LiXi-storage** [comment]
I'd suggest to use https://github.com/DDNStorage/monsystem_package to build an ISO for Collectd RPMs. An ISO will be generated with both RHEL6 and RHEL7 RPMs of collectd.

And you can download the generated ISO from here too: http://lustrefs.cn/monitor/

**Comment by LiXi-storage** [comment]
I'd suggest to use https://github.com/DDNStorage/monsystem_package to build an ISO for Collectd RPMs. An ISO will be generated with both RHEL6 and RHEL7 RPMs of collectd.

And you can download the generated ISO from here too: http://lustrefs.cn/monitor/

**Comment by LiXi-storage** [comment]
I'd suggest to use https://github.com/DDNStorage/monsystem_package to build an ISO for Collectd RPMs. An ISO will be generated with both RHEL6 and RHEL7 RPMs of collectd.

And you can download the generated ISO from here too: http://lustrefs.cn/monitor/

**Comment by martinvelez** [comment]
Thanks for replying.  I am going to download the ISO and check out the RPMS there.

**Comment by martinvelez** [comment]
In http://lustrefs.cn/monitor/, it notes that the ISO was generated on Jan 29, 2019.  What commit/version of DDNStorage/collectd is it using?  Is it using the most recent commit, fb3c10a222003bab3c6385415fdb2c860207e112, pushed on Sep 17, 2018?

I tried searching for this answer in **monsystem_package/esmon_build.conf** but it only shows an internal git repo and no specific commit.
```
collectd_git_url: ssh://root@server12:22/work/git/ddnj/collectd.git # Git URL to clone Collectd from
```

Also, is the HEAD of the master branch relatively stable?  In other words, is it safe to build and use the HEAD of master branch of this Github repo?

**Comment by LiXi-storage** [comment]
> In http://lustrefs.cn/monitor/, it notes that the ISO was generated on Jan 29, 2019. What commit/version of DDNStorage/collectd is it using?

You can find the Collectd RPMs under ISO directory XX/RPMS/rhel7/collectd/. And from the Collectd RPM names, you will be find the commit, e.g.

collectd-5.7.2.gfd0468a.ddn-7.el7.x86_64.rpm

The commit is fd0468a. And fd0468a is the latest version.

> Also, is the HEAD of the master branch relatively stable? In other words, is it safe to build and use the HEAD of master branch of this Github repo?
I just pushed another two patches into the Github repo which fix two problems. And the master-ddn branch of the Github repo will be synced as soon as possible. So yes, it is safe to use it.

**Comment by LiXi-storage** [comment]
Martin, I am closing this ticket. Please feel free to open another ticket if you find further problems.
