### ISSUE TITLE
Does not reconnect to influxdb 

### ISSUE THREAD

**Issue by Obihoernchen** [DDNStorage/collectd#5]
*   Version of collectd: `collectd-5.7.2.g8f2e7a9.ddn-7.el7.x86_64`
*   Operating system / distribution: CentOS 7.5

## Expected behavior

Collectd should try to reconnect and continue sending data if influxdb was down for a few seconds.

## Actual behavior

If influxdb goes down for a few seconds, collectd stops working and does not send any data anymore.

## Steps to reproduce

*   I don't know if this is necessary but we have 2 influxdb hosts defined:
```
LoadPlugin write_tsdb
<Plugin "write_tsdb">
    <Node "Node1">
        Host "10.0.0.1"
        Port "4242"
        DeriveRate true
    </Node>
    <Node "Node2">
        Host "10.0.0.2"
        Port "4242"
        DeriveRate true
    </Node>
</Plugin>
```
*   stop influxdb on one node
*   wait 3 minutes
*   start influxdb again
*   collectd stops sending any data and throws the following error ~1000 times in a single second:
```
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: send failed with status -1 (Success)
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: error with wt_send_message
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: Connecting to 10.0.0.2:4242 failed.
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: wt_callback_init failed.
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: error with wt_send_message
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: Connecting to 10.0.0.2:4242 failed.
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: wt_callback_init failed.
Mär 13 20:04:09 cr01o01 collectd[23538]: write_tsdb plugin: error with wt_send_message
```
Furthermore, if you define multiple `<Node>` elements the following error is thrown several times each start, but afterwards everything is working fine.
```
Mär 04 20:52:51 cr01o01 systemd[1]: Started Collectd statistics daemon.
Mär 04 20:52:51 cr01o01 collectd[2172]: write_tsdb plugin: wt_callback_init failed.
Mär 04 20:52:51 cr01o01 collectd[2172]: write_tsdb plugin: error with wt_send_message
Mär 04 20:52:51 cr01o01 collectd[2172]: write_tsdb plugin: wt_callback_init failed.
Mär 04 20:52:51 cr01o01 collectd[2172]: write_tsdb plugin: wt_callback_init failed.
Mär 04 20:52:51 cr01o01 collectd[2172]: write_tsdb plugin: error with wt_send_message
```

## Idea
As LustrePerfMon is using influxdb anyways you may also could switch to the new `write_influxdb_udp` plugin from collectd upstream? https://github.com/collectd/collectd/blob/master/src/write_influxdb_udp.c

**Comment by LiXi-storage** [comment]
Hi, I think it is a good idea to use write_influxdb_udp.c.

In order to do so, there are two ways. One way is to rebase this branch to master branch of Collectd. The other way is to port write_influxdb_udp.c to this branch. I prefer the first one since that would include other fixes/improvements/new plugins of master branch.

**Comment by Obihoernchen** [comment]
@LiXi-storage yes the first option sounds really good. Do you have any rough ETA on this?

**Comment by LiXi-storage** [comment]
@Obihoernchen 

We've rebased all the patches to latest master branch of Collectd. And we confirmed that it can be built successfully. We are trying to test it together with LustrePerfMon to confirm data can be collected as expected.

At the same time, it would be nice if you can test that branch and give feedback if anything isn't work as you expected. Thanks in advance.

The new branch:  https://github.com/DDNStorage/collectd/tree/LustrePerfMon-5.11.0

**Comment by LiXi-storage** [comment]
Issue fixed by 

https://github.com/DDNStorage/collectd/commit/c40e083bdeb51d964c3985ce78cf2a2f78ead996
